### ISSUE TITLE
Separate es6 completion

### ISSUE THREAD

**Issue by Kiura** [Stephn-R/ES6-Toolkit-for-Sublime#4]
Hello, is there any way to have separate sublime package for `es6` completion? since I (maybe others as well) use build systems and many features of the package are just duplications.

**Comment by stephnr** [comment]
Can you elaborate more on what you are asking for? Is it just a problem that there are duplicate snippet commands?

**Comment by Kiura** [comment]
No, there is no problem, It was just a suggestion to separate into several packages so they would be easier to maintain, and it would be better for users (search for es6 completion package, search for es compiler etc). And used my case as an example, apart from that great package

**Comment by stephnr** [comment]
I fail to see how that is better. I feel that one package with a compiler, snippets, and more is a much better and easier way to develop additional tools that are provided through Package Control.

-- 
Stephen Rodriguez

On January 30, 2016 at 2:43:46 PM, Kiura (notifications@github.com) wrote:

No, there is no problem, It was just a suggestion to separate into several packages so they would be easier to maintain, and it would be better for users (search for es6 completion package, search for es compiler etc). And used my case as an example, apart from that great package

**Comment by Kiura** [comment]
Ok, I guess we have different views on the subject )) I just needed completion part of the package (which works perfectly btw), and since i am using build system which compiles files as they change, the compilation part of the package is not needed for me at all, thats why I suggested to separate down into smaller packages.
