### ISSUE TITLE
Missing For Loop using Let

### ISSUE THREAD

**Issue by flyingduck92** [Stephn-R/ES6-Toolkit-for-Sublime#6]
I check this snippet inside the package. 
For Loop using Let snippet is inside of the snippet, but you have the wrong snippet. 
Instead of "For Loop using Let snippet", you put "Iterator using Let snippet" inside es6-let-for.sublime-snippet. So u are need 1 more snippet "Iterator using Let snippet files"

![ss](https://cloud.githubusercontent.com/assets/14885417/16897043/e47c9844-4bcf-11e6-8ab7-4aab310af027.png)

**Comment by stephnr** [comment]
Closed due to lack of use
