### ISSUE TITLE
New snippet

### ISSUE THREAD

**Issue by maurelian** [Stephn-R/ES6-Toolkit-for-Sublime#7]
How would you feel about a PR to add a standard callback formatted arrow function like 

```
(err, result) => {
 // do something... 
}
```

Or is there an easy way to add my own snippets locally?

**Comment by stephnr** [comment]
Definitely a very easy thing to do. Would you like to provide a PR with this new snippet? :)

**Comment by maurelian** [comment]
sorry for the slow reply, I'm currently testing out Atom editor, which is more common among my team. I'll close this, thanks!
